# Generated by Django 4.2 on 2025-05-26 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ankiety', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pytanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc_pytania', models.CharField(max_length=200)),
                ('data_publikacji', models.DateTimeField(verbose_name='data publikacji')),
            ],
        ),
        migrations.CreateModel(
            name='Wybor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc_wyboru', models.CharField(max_length=200)),
                ('liczba_glosow', models.IntegerField(default=0)),
                ('pytanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ankiety.pytanie')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
