# Generated by Django 5.2.2 on 2025-06-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_notatki_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notatki',
            name='data',
        ),
    ]
